services:
  api:
    container_name: api
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/cookingAPI
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=cookingAPI
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx/dev/data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/dev/cert/localhost.crt:/etc/ssl/ca.crt
      - ./nginx/dev/cert/localhost.key:/etc/ssl/ca.key
    depends_on:
      - api

volumes:
  postgres-db:
