"""user best score ondelete

Revision ID: 8c256468fa06
Revises: ce28b0f6ff31
Create Date: 2024-11-04 00:08:28.441621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c256468fa06'
down_revision: Union[str, None] = 'ce28b0f6ff31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Scores_user_id_fkey', 'Scores', type_='foreignkey')
    op.create_foreign_key(None, 'Scores', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Scores', type_='foreignkey')
    op.create_foreign_key('Scores_user_id_fkey', 'Scores', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###
