"""user id unique fix

Revision ID: ce28b0f6ff31
Revises: 9c16c430d3a6
Create Date: 2024-11-03 22:13:07.078848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce28b0f6ff31'
down_revision: Union[str, None] = '9c16c430d3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Scores', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Scores', type_='unique')
    # ### end Alembic commands ###
